---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "development"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
